website:
  title: "Preethi Ganta"
  navbar:
    right:
      - text: "Projects"
        href: projects.qmd       # ← add this
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/preethi-g-4b414b28b
      - icon: github
        href: https://github.com/Preethiganta07



